/**
 * _overlay_example — demonstrates the `overlay: { register, code }` opt-in.
 *
 * Disabled by default. Apply() is a no-op: the entire contribution rides on
 * the sibling ccpatch-overlay.mjs file generated by runner/overlay-builder.mjs
 * and loaded once by core/overlay_loader at bundle startup.
 *
 * Anything published here is reachable via __ccpRequire('overlay-example').
 *
 * The leading underscore in the filename makes the patch-verification test
 * loop skip this file (it's a documentation example, not a real patch).
 */

export default {
  name: '_overlay_example',
  version: '1.0.0',
  category: 'optional',
  description: 'Example: publish a simple value into the __ccp* registry via the overlay file (no bundle anchor).',
  capabilities: [],
  enabled: false,
  // Manifest still requires a verify block. The overlay-loader's own verify
  // asserts the require call is in place; for this example we just assert the
  // shebang is still in the bundle (a true no-op apply).
  verify: { present: '#!/usr/bin/env node', weak: true },
  overlay: {
    register: 'overlay-example',
    code: `
      return {
        version: 1,
        hello() { return 'hello from overlay'; },
      };
    `,
  },
  // apply() is intentionally a no-op — all logic lives in the overlay file.
  apply: (code) => code,
};
