/**
 * standup_command_shim — git-activity → standup prompt composer.
 *
 * Shims-as-patches (rule 6): the standup_command patch injects only a thin
 * wrapper around the React submit useCallback. ALL real logic — argument
 * parsing, shelling out to git in the CLI's cwd, and prompt composition — lives
 * here so the bundle splice stays small.
 *
 * Public surface (installed on globalThis at boot):
 *   globalThis.__ccpStandupBuildPrompt(rawInput) -> string | null
 *     • rawInput is the raw queued-command text (e.g. "/standup" or "/standup 3").
 *     • Returns the generated standup prompt to SUBMIT in place of the slash
 *       command, or null when the input is not a /standup invocation (so the
 *       caller leaves the input untouched).
 *     • Never throws: any git failure degrades to a "git data was unavailable"
 *       prompt rather than erroring (fail open, rule 4).
 *
 * The function is synchronous and uses child_process.execFileSync with a short
 * timeout so it can run inline inside the submit callback without awaiting.
 */

import { createRequire } from 'node:module';

// In the injected bundle copy, `require` is in scope (CJS). Here in ESM we
// reconstruct it so the shim's behavior matches the bundle's at test time.
const _require = createRequire(import.meta.url);

const STANDUP_RE = /^\/standup(?:\s+(\d+))?\s*$/i;

/** Run git args in cwd, returning trimmed stdout or null on any failure. */
function git(cp, args) {
  try {
    const out = cp.execFileSync('git', args, {
      cwd: process.cwd(),
      encoding: 'utf8',
      timeout: 5000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return typeof out === 'string' ? out.trim() : null;
  } catch (_e) {
    return null;
  }
}

/**
 * Compose the standup prompt from recent git activity.
 * @param {string} rawInput raw queued-command text
 * @returns {string|null}
 */
export function buildStandupPrompt(rawInput) {
  try {
    const m = STANDUP_RE.exec(String(rawInput || '').trim());
    if (!m) return null;

    const days = Math.max(1, m[1] ? parseInt(m[1], 10) || 1 : 1);
    const dayWord = days === 1 ? 'day' : 'days';

    let cp;
    try {
      cp = _require('node:child_process');
    } catch (_e) {
      try { cp = _require('child_process'); } catch (_e2) { cp = null; }
    }

    const instruction =
      'Write a concise daily standup update (Yesterday / Today / Blockers) ' +
      'from the git activity above. Keep it to a few bullet points per section.';

    if (!cp) {
      return (
        `Recent git activity for the last ${days} ${dayWord}:\n` +
        `(git data was unavailable — child_process could not be loaded.)\n\n` +
        instruction
      );
    }

    const since = `${days} ${dayWord} ago`;
    const log = git(cp, ['log', `--since=${since}`, '--pretty=format:%h %s']);

    // Churn: try the `@{N.days.ago}` reflog ref first; fall back to --shortstat
    // over the same window when the ref doesn't resolve (shallow clones, fresh
    // repos, detached HEAD, or non-git dirs).
    let churn = git(cp, ['diff', '--stat', `@{${days}.days.ago}`]);
    if (churn == null) {
      churn = git(cp, ['log', `--since=${since}`, '--shortstat', '--pretty=format:']);
      if (churn != null) churn = churn.replace(/\n{2,}/g, '\n').trim();
    }

    const isRepo = git(cp, ['rev-parse', '--is-inside-work-tree']) === 'true';

    if (!isRepo) {
      return (
        `Recent git activity for the last ${days} ${dayWord}:\n` +
        `(git data was unavailable — not a git repository, or git is not installed.)\n\n` +
        instruction
      );
    }

    const commitsBlock =
      log && log.length ? log : '(no commits in this window)';
    const churnBlock =
      churn && churn.length ? churn : '(no diff stats available)';

    return (
      `Recent git activity for the last ${days} ${dayWord} ` +
      `(generated by the /standup command):\n\n` +
      `Commits:\n${commitsBlock}\n\n` +
      `Churn:\n${churnBlock}\n\n` +
      instruction
    );
  } catch (_e) {
    // Absolute backstop — never throw into the submit path.
    return (
      'Recent git activity:\n(git data was unavailable — an internal error ' +
      'occurred while gathering it.)\n\n' +
      'Write a concise daily standup update (Yesterday / Today / Blockers) ' +
      'from the git activity above.'
    );
  }
}

/** Install the composer on globalThis (idempotent, fail-open). */
export function installStandupComposer(g) {
  try {
    const target = g || globalThis;
    if (target.__ccpStandupBuildPrompt) return;
    target.__ccpStandupBuildPrompt = buildStandupPrompt;
  } catch (_e) { /* fail open */ }
}

// `capabilities` is declared for the capability-honesty lint: this shim shells
// out to git via child_process (exec). It is underscore-prefixed so the patch
// loader ignores it — it is a reference/test surface, not an applied patch.
export default { capabilities: ['exec'], buildStandupPrompt, installStandupComposer };
