/**
 * overlay_loader — single bundle anchor that loads a sibling overlay file.
 *
 * Magisk-style "overlay, don't mutate": instead of every patch carving its own
 * anchor into the bundle, this patch injects exactly ONE require near the top
 * of the IIFE that pulls in `ccpatch-overlay.mjs` (generated by the runner
 * alongside the patched bundle). Per-extension shim code lives in that file
 * and registers via __ccpProvide / __ccpRequire instead of bundle anchors.
 *
 * Trade-off: one extra file ships next to the bundle, in exchange for fewer
 * bundle anchors that can drift across upstream versions.
 *
 * Ordering:
 *   phase: 'pre' — runs before esm_compat (post) rewrites the IIFE tail.
 *   We anchor on the CJS-IIFE opening so `require` is the IIFE's local
 *   parameter and is available even after esm_compat rewrites the call to
 *   pass `__hm_require`.
 */

const SENTINEL = '/* [ccpatch overlay-loader] */';

// Integrity-checking loader block injected into the bundle.
// Uses synchronous fs/crypto so it runs safely at boot before the event loop.
const hook =
  `${SENTINEL} try { ` +
  `(function () { ` +
  `var __ccp_op = require('path').resolve(__dirname, 'ccpatch-overlay.mjs'); ` +
  `var __ccp_sp = __ccp_op + '.sha256'; ` +
  `var __ccp_fs = require('fs'); ` +
  `if (__ccp_fs.existsSync(__ccp_sp)) { ` +
  `var __ccp_expected = __ccp_fs.readFileSync(__ccp_sp, 'utf8').trim(); ` +
  `var __ccp_actual = require('crypto').createHash('sha256').update(__ccp_fs.readFileSync(__ccp_op)).digest('hex'); ` +
  `if (__ccp_actual !== __ccp_expected) { ` +
  `process.stderr.write('[ccpatch] INTEGRITY FAIL: overlay file hash mismatch — possible tampering. Skipping overlay load.\\n'); ` +
  `return; ` +
  `} ` +
  `} else { ` +
  `process.stderr.write('[ccpatch] overlay integrity sidecar not found — skipping hash check (old build).\\n'); ` +
  `} ` +
  `require('./ccpatch-overlay.mjs'); ` +
  `})(); ` +
  `} catch (e) { if (e && e.code !== 'MODULE_NOT_FOUND') console.error('[ccpatch] overlay load failed:', e && e.message); }\n`;

const __cjsIife__ = '(function(exports, require, module, __filename, __dirname) {';

export default {
  name: 'overlay_loader',
  version: '1.0.0',
  category: 'infrastructure',
  description: 'Overlay loader — single anchor that loads ./ccpatch-overlay.mjs (Magisk-style overlay)',
  capabilities: ['fs'],
  phase: 'pre',
  required: true,
  verify: {
    present: ["require('./ccpatch-overlay.mjs')", SENTINEL],
    count: { present: 2 },
  },
  apply: (code) => {
    if (code.includes(SENTINEL)) return code; // idempotent
    if (code.includes(__cjsIife__)) {
      return code.replace(__cjsIife__, () => __cjsIife__ + ' ' + hook);
    }
    // Native-ESM fallback: inject after shebang using createRequire.
    const shebang = '#!/usr/bin/env node';
    if (code.startsWith(shebang)) {
      const esmHook =
        `${SENTINEL} try { ` +
        `const { createRequire: __ccpCR } = await import('node:module'); ` +
        `__ccpCR(import.meta.url)('./ccpatch-overlay.mjs'); ` +
        `} catch (e) { if (e && e.code !== 'MODULE_NOT_FOUND') console.error('[ccpatch] overlay load failed:', e && e.message); }\n`;
      const nl = code.indexOf('\n') + 1;
      return code.slice(0, nl) + esmHook + code.slice(nl);
    }
    console.warn('  [!] overlay_loader: no anchor found — skipping');
    return code;
  },
};
