/**
 * Overlay builder — generates the sibling `ccpatch-overlay.mjs` file loaded
 * by the core/overlay_loader patch.
 *
 * Each patch may opt-in by exporting:
 *
 *   export const overlay = {
 *     register: 'name-published-into-__ccpProvide',
 *     code: `// JS run at overlay load time; has access to __ccpProvide / __ccpRequire`,
 *   };
 *
 * The builder collects these from all enabled patches and emits a single
 * file with one __ccpProvide() call per opt-in patch. The file is loaded
 * once by the in-bundle overlay-loader at startup.
 *
 * ── Dev mode (hot-reload) ────────────────────────────────────────────────
 * When `opts.dev === true`, the emitted overlay file is a thin loader: each
 * patch's real shim code is written to `ccpatch-overlay-shims/<name>.mjs`
 * and the overlay registers a Proxy that re-requires the shim file on every
 * property access (busting Node's require.cache first). This enables
 * Xposed/LSPosed-style hot-reload: editing a shim file is picked up on the
 * next __ccpRequire() call without re-patching the bundle.
 *
 * In dev mode, the patch's `code` block must be a valid top-level module
 * body that ends with `module.exports = { ... }` (not a function body with
 * `return ...`). The non-dev path wraps `code` in an IIFE and uses its
 * return value; the dev path treats `code` as a CommonJS module body.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { topoSort } from './runner.mjs';

export function collectOverlayPatches(patches, patchNames) {
  const ordered = topoSort(patchNames, patches);
  const out = [];
  for (const name of ordered) {
    const patch = patches[name];
    if (!patch || !patch.overlay) continue;
    const { register, code } = patch.overlay;
    if (typeof register !== 'string' || !register
      || typeof code !== 'string' || !code) continue;
    out.push({ name, register, code });
  }
  return out;
}

const SHIM_DIR_NAME = 'ccpatch-overlay-shims';

/**
 * Build the overlay file source. Returns a string (or null if no patches
 * declare `overlay`). Each opt-in patch contributes one __ccpProvide() call
 * whose value is the result of an IIFE wrapping the patch's `code` block.
 *
 * @param {object}  patches      registry { name -> patch }
 * @param {string[]} patchNames  selected patch names
 * @param {object}  [opts]
 * @param {boolean} [opts.dev]   emit thin hot-reload loader format
 */
export function buildOverlay(patches, patchNames, opts = {}) {
  const entries = collectOverlayPatches(patches, patchNames);
  if (entries.length === 0) return null;
  if (opts.dev) return buildDevOverlay(entries);
  return buildProdOverlay(entries);
}

function buildProdOverlay(entries) {
  const parts = [
    '// ══════════════════════════════════════════════════════════════════════════',
    '// ccpatch overlay — generated by runner/overlay-builder.mjs',
    '//',
    '// Loaded once at bundle startup by the core/overlay_loader patch via',
    '//   require(\'./ccpatch-overlay.mjs\')',
    '//',
    '// Each block below comes from a patch that declared `overlay: { register, code }`',
    '// and publishes its value through the __ccpProvide / __ccpRequire registry.',
    '// ══════════════════════════════════════════════════════════════════════════',
    '',
  ];
  for (const { name, register, code } of entries) {
    parts.push(`// ── [overlay] ${name} → __ccpProvide(${JSON.stringify(register)}) ──`);
    parts.push(`try {`);
    parts.push(`  const __ccp_value__ = (function () {`);
    parts.push(code.trim());
    parts.push(`  })();`);
    parts.push(`  if (typeof globalThis.__ccpProvide === 'function') {`);
    parts.push(`    globalThis.__ccpProvide(${JSON.stringify(register)}, { producer: ${JSON.stringify(name)}, version: 1, value: __ccp_value__ });`);
    parts.push(`  } else {`);
    parts.push(`    (globalThis.__ccpOverlayPending = globalThis.__ccpOverlayPending || []).push({ register: ${JSON.stringify(register)}, producer: ${JSON.stringify(name)}, value: __ccp_value__ });`);
    parts.push(`  }`);
    parts.push(`} catch (e) { console.error('[ccpatch overlay] "${name}" failed:', e && e.message); }`);
    parts.push('');
  }
  return parts.join('\n');
}

function buildDevOverlay(entries) {
  const parts = [
    '// ══════════════════════════════════════════════════════════════════════════',
    '// ccpatch overlay — DEV MODE (hot-reload) — generated by runner/overlay-builder.mjs',
    '//',
    '// Each Proxy below re-requires its shim file from ./ccpatch-overlay-shims/',
    `// on every property access, busting Node's require.cache. Editing a shim`,
    '// file therefore takes effect at the next __ccpRequire(name)[prop] call.',
    '//',
    '// This format is for dev iteration ONLY. Re-run `ccpatch apply` without',
    '// --dev to produce a production overlay (no per-access cache busting).',
    '// ══════════════════════════════════════════════════════════════════════════',
    '',
    `console.log('[ccpatch] DEV MODE overlay — shims hot-reload from ./${SHIM_DIR_NAME}/');`,
    '',
  ];
  for (const { name, register } of entries) {
    const shimFile = `${name}.cjs`;
    parts.push(`// ── [overlay-dev] ${name} → __ccpProvide(${JSON.stringify(register)}) ──`);
    parts.push(`try {`);
    parts.push(`  const __ccp_path__ = require('path').join(__dirname, ${JSON.stringify(SHIM_DIR_NAME)}, ${JSON.stringify(shimFile)});`);
    parts.push(`  const __ccp_value__ = new Proxy({}, {`);
    parts.push(`    get(_t, prop) {`);
    parts.push(`      try { delete require.cache[require.resolve(__ccp_path__)]; } catch (_) {}`);
    parts.push(`      const mod = require(__ccp_path__);`);
    parts.push(`      const v = mod && typeof mod === 'object' ? mod[prop] : undefined;`);
    parts.push(`      return typeof v === 'function' ? v.bind(mod) : v;`);
    parts.push(`    },`);
    parts.push(`    has(_t, prop) {`);
    parts.push(`      try { delete require.cache[require.resolve(__ccp_path__)]; } catch (_) {}`);
    parts.push(`      const mod = require(__ccp_path__);`);
    parts.push(`      return mod && typeof mod === 'object' && (prop in mod);`);
    parts.push(`    },`);
    parts.push(`  });`);
    parts.push(`  if (typeof globalThis.__ccpProvide === 'function') {`);
    parts.push(`    globalThis.__ccpProvide(${JSON.stringify(register)}, { producer: ${JSON.stringify(name)}, version: 1, value: __ccp_value__ });`);
    parts.push(`  } else {`);
    parts.push(`    (globalThis.__ccpOverlayPending = globalThis.__ccpOverlayPending || []).push({ register: ${JSON.stringify(register)}, producer: ${JSON.stringify(name)}, value: __ccp_value__ });`);
    parts.push(`  }`);
    parts.push(`} catch (e) { console.error('[ccpatch overlay-dev] "${name}" failed:', e && e.message); }`);
    parts.push('');
  }
  return parts.join('\n');
}

/**
 * Emit the overlay file (and, in dev mode, the per-patch shim files) next to
 * the patched bundle. Returns:
 *
 *   { overlayPath, shimDir | null, shimPaths: string[] }   on success
 *   null                                                   when nothing to emit
 *
 * Safe to call repeatedly (used by `ccpatch watch`).
 */
export function emitOverlay(patches, patchNames, outputDir, opts = {}) {
  const entries = collectOverlayPatches(patches, patchNames);
  if (entries.length === 0) return null;
  fs.mkdirSync(outputDir, { recursive: true });

  const overlayPath = path.join(outputDir, 'ccpatch-overlay.mjs');
  const src = opts.dev ? buildDevOverlay(entries) : buildProdOverlay(entries);
  fs.writeFileSync(overlayPath, src, 'utf8');

  // Emit SHA-256 integrity sidecar — non-fatal if it fails.
  let sidecarPath = null;
  try {
    const hex = createHash('sha256').update(src, 'utf8').digest('hex');
    sidecarPath = overlayPath + '.sha256';
    fs.writeFileSync(sidecarPath, hex + '\n', 'utf8');
  } catch (e) {
    console.warn('[ccpatch] overlay integrity sidecar write failed:', e && e.message);
    sidecarPath = null;
  }

  if (!opts.dev) {
    return { overlayPath, sidecarPath, shimDir: null, shimPaths: [] };
  }

  const shimDir = path.join(outputDir, SHIM_DIR_NAME);
  fs.mkdirSync(shimDir, { recursive: true });
  const shimPaths = [];
  for (const { name, code } of entries) {
    const shimPath = path.join(shimDir, `${name}.cjs`);
    const header =
      `// ccpatch dev shim for "${name}" — edit and save to hot-reload.\n` +
      `// Must be a valid CommonJS module body; export shim API via module.exports.\n` +
      `// Re-required on every __ccpRequire(...) property access.\n\n`;
    fs.writeFileSync(shimPath, header + code.trim() + '\n', 'utf8');
    shimPaths.push(shimPath);
  }
  return { overlayPath, sidecarPath, shimDir, shimPaths };
}

/**
 * Write the overlay file next to the patched bundle. Returns the path written
 * or null when there is nothing to write.
 *
 * Back-compat thin wrapper around `emitOverlay`.
 */
export function writeOverlay(patches, patchNames, outputDir, opts = {}) {
  const r = emitOverlay(patches, patchNames, outputDir, opts);
  return r ? r.overlayPath : null;
}
