/**
 * Preload builder — generates a Node.js --require preload script from
 * patches that declare `preload: true` and `preloadCode`.
 *
 * Why preloads?
 *   Patches that only wrap globalThis.fetch or process.stdin don't need to
 *   modify the bundle at all. Running them as a --require preload means:
 *     - Zero anchor exposure for these patches (no bundle text to drift)
 *     - The bundle itself is untouched (easier auditing, smaller diff)
 *     - Preload patches compose independently of bundle version
 *
 * Usage (CLI):
 *   node runner/cli.mjs <input.js> <output.js> --preload preload.mjs
 *
 * Usage (runtime):
 *   node --require ./preload.mjs ./releases/<version>/cli.patched.js
 *
 * Patches eligible for preload:
 *   - Must set `preload: true` in their manifest
 *   - Must expose a `preloadCode` string (the raw JS to inject)
 *   - Must not rely on any minified bundle-internal identifier
 */

import { topoSort } from './runner.mjs';

/**
 * Build a preload script from all preload-capable patches in patchNames.
 *
 * @param {Record<string, object>} patches    - Loaded patch map (name → module)
 * @param {string[]}               patchNames - Enabled patch names to consider
 * @returns {string|null} Generated preload source, or null if no preload patches found
 */
export function buildPreload(patches, patchNames) {
  const preloadCandidates = patchNames.filter(n => patches[n]?.preload);
  if (preloadCandidates.length === 0) return null;

  const ordered = topoSort(preloadCandidates, patches);

  const parts = [
    '// ══════════════════════════════════════════════════════════════════════════',
    '// ccpatch preload — generated by runner/preload-builder.mjs',
    '// Usage: node --require <this-file> <patched-cli.js>',
    '//',
    '// This file contains patches that do NOT modify the bundle — they only wrap',
    '// globalThis APIs before cli.js starts. Safe to re-use across bundle versions.',
    '// ══════════════════════════════════════════════════════════════════════════',
    '',
  ];

  for (const name of ordered) {
    const patch = patches[name];
    if (!patch?.preload) continue;
    const code = typeof patch.preloadCode === 'function' ? patch.preloadCode() : patch.preloadCode;
    if (!code || typeof code !== 'string') continue;
    parts.push(`// ── [preload] ${name}: ${patch.description} ──`);
    parts.push(code.trim());
    parts.push('');
  }

  return parts.join('\n');
}
